server:
  port: 8080

  #servlet上下文路径，默认是/
  servlet:
    context-path: /im_bird_sys

spring:
    datasource:
      name: im_bird_sys
      #连接数据库的url
      url: jdbc:mysql://119.91.87.151:3307/im_bird

      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

      username: root
      password: 21066157g

      #监控统计的设置
      filters: stat

      #初始化连接
      inital-size: 2
      #最大空闲连接
      max-idle: 10
      #最小空闲
      min-idle: 1
      #获取连接超时的等待时间
      max-wait: 60000
      #最大活动连接数
      max-active: 20
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-evict-runs-millis: 60000
      #一个连接在连接池中最小生存空间
      min-evictable-time-millis: 300000
      #验证连接有效的sql
      validation-query: select 'x'
      #指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，从连接池中去除
      test-while-idle: true
      #借出连接时不要测试，否则影响性能
      test-on-borrow: false
    mvc:
      view:
        prefix: /WEB-INF/pages/
        suffix: .jsp

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 119.91.87.151:22122